modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"
issueTrackerURL = "https://github.com/Tki-sor/MemorySweep/issues"
[[mods]]
modId = "memorysweep"
version = "${version}"
displayName = "MemorySweep"
displayURL="https://www.curseforge.com/minecraft/mc-mods/memorysweep"
logoFile = "icon.png"
authors = "Tki_sor"
description = '''

'''
[[dependencies.memorysweep]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.memorysweep]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.21)"
ordering = "NONE"
side = "BOTH"
[[dependencies.memorysweep]]
modId = "cloth_config"
mandatory = true
versionRange = "[11.0,)"
ordering = "NONE"
side = "BOTH"