plugins {
    id 'java-library'
    id 'maven-publish'
}

group = project.maven_group
version = project.mod_version

repositories {
    maven { url "https://maven.fabricmc.net/" }
    maven { url "https://maven.minecraftforge.net/" }
    maven { url "https://maven.neoforged.net/releases/" }
    mavenCentral()
}

base {
    archivesName = "${rootProject.archives_name}-universal"
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

tasks.withType(JavaCompile).configureEach {
    options.release = 8
    options.encoding = 'UTF-8'
}

dependencies {
    compileOnly "net.fabricmc:sponge-mixin:0.15.5+mixin.0.8.7"
}

processResources {
    inputs.property 'version', project.version
    filesMatching(['fabric.mod.json', 'META-INF/mods.toml', 'META-INF/neoforge.mods.toml']) {
        expand version: project.version
    }
}

jar {
    archiveClassifier = ''
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    exclude 'net/fabricmc/api/ModInitializer.class'
    exclude 'net/minecraftforge/fml/common/Mod.class'
    exclude 'net/neoforged/fml/common/Mod.class'
    manifest {
        attributes(
                'Specification-Title': 'MemorySweep Universal',
                'Specification-Version': project.version,
                'Implementation-Version': project.version,
                'MixinConfigs': 'memorysweep-universal.mixins.json'        )
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
}
