modLoader="javafml"
loaderVersion="[43,)"
license="MIT License"
issueTrackerURL="https://github.com/Tki-sor/MemorySweep/issues"
[[mods]]
modId="memorysweep"
version="1.19.3-0.8"
displayName="MemorySweep"
logoFile="memorysweep.png"
authors="Tki_sor"
displayURL="https://www.curseforge.com/minecraft/mc-mods/memorysweep"
description='''
This is a mod for memory cleaner.
'''
[[dependencies.memorysweep]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.memorysweep]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
