modLoader="javafml" #mandatory
loaderVersion="[36,)"
license="MIT License"
issueTrackerURL="https://github.com/Tki-sor/MemorySweep/issues"
[[mods]] #mandatory
modId="memorysweep" #mandatory
version="1.16.5-0.8" #mandatory
displayName="memorysweep" #mandatory
logoFile="memorysweep.png" #optional
authors="Tki_sor" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/memorysweep"
description='''
This is a mod for memory cleaner.
'''
[[dependencies.memorysweep]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[36,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.memorysweep]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
