modLoader="javafml"
loaderVersion="[44,)"
license="MIT License"
issueTrackerURL="https://github.com/Tki-sor/MemorySweep/issues"
[[mods]]
modId="memorysweep"
version="1.19.3-0.6"
displayName="MemorySweep"
logoFile="memorysweep.png"
authors="Tki_sor"
description='''
This is a mod for memory cleaner.
'''
[[dependencies.memorysweep]]
    modId="forge"
    mandatory=true
    versionRange="[44,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.memorysweep]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"
